# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Stage 1: Build the application
FROM node:18.17-alpine AS builder

# Install pnpm
RUN npm install -g pnpm

# Set the working directory
WORKDIR /app

# Copy the necessary files
COPY . .

# Install dependencies and build the project
RUN pnpm install --frozen-lockfile && pnpm run build

# Stage 2: Run the application
FROM node:18.17-alpine AS runtime

# Set the working directory
WORKDIR /app

# Copy the built application and necessary files
COPY --from=builder /app/dist /app/dist
COPY --from=builder /app/package.json /app/package.json
COPY --from=builder /app/pnpm-lock.yaml /app/pnpm-lock.yaml

# Install only production dependencies
RUN pnpm install --prod --frozen-lockfile

# Specify the entrypoint for the container
ENTRYPOINT ["node", "dist/index.js"]
