# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use Node.js 18 as the base image
FROM node:18-slim AS builder

# Install pnpm
RUN npm install -g pnpm

# Set the working directory
WORKDIR /app

# Copy the package.json and pnpm-lock.yaml to the working directory
COPY package.json pnpm-lock.yaml ./

# Install the dependencies
RUN pnpm install

# Copy the rest of the application code
COPY . .

# Build the project
RUN pnpm run build

# Create the final image from the base Node.js image
FROM node:18-slim

# Set the working directory
WORKDIR /app

# Copy the built files from the builder stage
COPY --from=builder /app/ /app/

# Set environment variables
ENV TEMBO_API_KEY=your_tembo_api_key

# Set the entrypoint to run the server
ENTRYPOINT ["node", "dist/index.js"]
